trigger:
  branches:
    include:
      - main

variables:
  node_version: '18.x'
  app_location: '/'
  output_location: 'build'
  dev_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_DEV)
  prod_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_PROD)

stages:
- stage: Build
  displayName: 'Build React App'
  jobs:
    - job: BuildJob
      displayName: 'Build Job'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: NodeTool@0
          inputs:
            versionSpec: '$(node_version)'
        - script: |
            npm install
            npm run build
          displayName: 'Install and Build'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(output_location)'
            ArtifactName: 'react-build'
            publishLocation: 'Container'
